name: Reminders
version: 3.0.0
main: me.caleb.reminders.Reminders
author: c10coding

commands:
  reminders:
    description: Reminders command
permission:
  reminders.use:
    default: op
    description: "Allows admin usage of commands"

    
       