#Reminders
Prefix: '&7[&bReminder&7]'
Reminders:
  Strings:
#Time for Reminders
Time: 6000 
#Whenever someone needs help, it does this
#Previous index that was drawn
Prev:
Help:
- Do &6/reminders add [reminder] &a to add a reminder

- Do &6/reminders remove [#] &a to remove a reminder

- Do &6/reminders edit [#] [#] &a to edit a reminder

- Do &6/reminders list &a to list all the reminders

- Do &6/reminders settime [# of ticks] &a to set the interval between each reminder (&cMake sure you do /plugman reload Reminders for changes to take effect)
  
  